Repository sifiorg/sifi, pull requests merged in 2023-10, with the labels that each got.

#273 fix(frontend): handle multichain quote query culling
  packages/frontend/src/hooks/useCullQueries.tsx
  packages/frontend/src/hooks/useQuote.tsx
  packages/frontend/src/utils/queries.tsx
Labels: bug

#275 fix(frontend): always reset 'toAmount' value on input change
  packages/frontend/src/hooks/useQuote.tsx
Labels: bug

#276 feat(frontend): only retry once on failed quote
  packages/frontend/src/hooks/useQuote.tsx
Labels: ux

#309 fix(frontend): fetch token by address
  packages/frontend/src/providers/TokensProvider.tsx
Labels: bug

#335 feat(frontend): filter bsc name
  packages/frontend/src/utils/chains.ts
Labels: frontend

#342 fix(frontend): use routes for referral links
  packages/frontend/src/App.tsx
  packages/frontend/src/hooks/useReferrer.ts
  packages/frontend/src/hooks/useSyncTokenUrlParams.ts
  packages/frontend/src/utils/routes.ts
Labels: bug

#356 fix(hadhat): fix ci
  .github/workflows/ci-safe-to-test.yml
Labels: safe to test

#359 fix(hardhat): add missing foundry rpcs
  packages/hardhat/foundry.toml
Labels: safe to test

#369 feat(frontend): add browser wallet icons
  packages/frontend/package.json
  packages/frontend/src/components/ConnectWallet/ConnectWallet.tsx
  packages/frontend/src/components/HeaderMenu/HeaderMenu.tsx
  pnpm-lock.yaml
Labels: frontend
